### PR TITLE
Check if Metadata has content

### PR DESCRIPTION
**Pull request by trichask**
If content exists and has zero length, then an exception is thrown

### CODE REVIEW

**Comment by KitaitiMakoto** [comment]
Thanks for the patch!

**Comment by trichask** [comment]
You are most welcome!

In order to avoid [diamond shape](http://stackoverflow.com/questions/16666089/whats-the-difference-between-git-merge-and-git-rebase?answertab=active#tab-top), you could do it this way:

``` bash
git remote add trichask https://github.com/trichask/PHP-EPUBParser.git
git fetch trichask/master
git merge trichask/master --ff-only
git push origin master
```

**Comment by KitaitiMakoto** [comment]
Thanks for useful information.
But I don't feel any problem about diamond shape. So, I keep the merge commit.

**Comment by trichask** [comment]
Cool :+1:

**Pull request merged**
